name: Trigger on Issue event
on:
  issues:
    types: [opened]
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: echo Issue
        run: 'echo "New Issue #${{ github.event.issue.number }}: ${{ github.event.issue.title }}"'
